### ISSUE TITLE
dangerous script

### ISSUE THREAD

**Issue by josephworks** [braddevans/powershell-scripts#1]
script.ps1 is very dangerous. i tested it on my computer and it deleted all of my files

**Comment by braddevans** [comment]
the last time i was updating these scripts was 6 months ago when i was first learning how to use powershell and Script.ps1 was the first one so i'm sorry that the files got deleted,
+ in some cases i always check what the Powershell scripts do and run before I run them.

**Comment by josephworks** [comment]
LOL! its ok, i was using virtual machine with backups
